# -*- coding: utf-8 -*-
"""graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqjp-Yj195vm4F1teuHDoneAx9r9eEZo
"""

import csv
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

N         = []
linear_ns = []
bst_ns    = []
rbtree_ns = []
hash_ns   = []
mmap_ns   = []

with open("search_times.csv", newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        N.append(int(row["N"]))
        linear_ns.append(int(row["linear_ns"]) / 1000)   # нс → мкс
        bst_ns.append(int(row["bst_ns"])    / 1000)
        rbtree_ns.append(int(row["rbtree_ns"]) / 1000)
        hash_ns.append(int(row["hash_ns"])   / 1000)
        mmap_ns.append(int(row["multimap_ns"]) / 1000)

# Порог разбивки на два графика
SPLIT = 50000

def split(data):
    lo = [(n, v) for n, v in zip(N, data) if n <= SPLIT]
    hi = [(n, v) for n, v in zip(N, data)]
    return lo, hi

lin_lo, lin_hi   = split(linear_ns)
bst_lo, bst_hi   = split(bst_ns)
rb_lo,  rb_hi    = split(rbtree_ns)
ht_lo,  ht_hi    = split(hash_ns)
mm_lo,  mm_hi    = split(mmap_ns)

ALGORITHMS = [
    ("Линейный",    lin_lo, lin_hi,  "#e74c3c", "o"),
    ("BST",         bst_lo, bst_hi,  "#3498db", "s"),
    ("КЧ-дерево",   rb_lo,  rb_hi,   "#2ecc71", "^"),
    ("Хеш-таблица", ht_lo,  ht_hi,   "#f39c12", "D"),
    ("std::multimap", mm_lo, mm_hi,  "#9b59b6", "v"),
]

XLABEL = "Размер массива (N)"
YLABEL = "Время (мс)"

# График 1
fig, ax = plt.subplots(figsize=(10, 6))
for label, lo, _, color, marker in ALGORITHMS:
    xs = [p[0] for p in lo]
    ys = [p[1] for p in lo]
    ax.plot(xs, ys, label=label, color=color, marker=marker,
            markersize=6, linewidth=1.8)

ax.set_title("Сравнение алгоритмов поиска (N ≤ 50 000)", fontsize=14)
ax.set_xlabel(XLABEL)
ax.set_ylabel(YLABEL)
ax.legend()
ax.grid(True, linestyle="--", alpha=0.5)
ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f"{int(x):,}".replace(",", " ")))
plt.tight_layout()
plt.savefig("plot_small.png", dpi=150)
plt.close()
print("Сохранён plot_small.png")

# График 2
fig, ax = plt.subplots(figsize=(10, 6))
for label, _, hi, color, marker in ALGORITHMS:
    xs = [p[0] for p in hi]
    ys = [p[1] for p in hi]
    ax.plot(xs, ys, label=label, color=color, marker=marker,
            markersize=6, linewidth=1.8)

ax.set_title("Сравнение алгоритмов поиска (все N)", fontsize=14)
ax.set_xlabel(XLABEL)
ax.set_ylabel(YLABEL)
ax.legend()
ax.grid(True, linestyle="--", alpha=0.5)
ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f"{int(x):,}".replace(",", " ")))
plt.tight_layout()
plt.savefig("plot_all.png", dpi=150)
plt.close()
print("Сохранён plot_all.png")